name: stepsic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - toml
  - tabulate
  - h5py
  - numpy
  - scipy
  - astropy
  - camb
  - matplotlib
  - seaborn
  - pip
  - pip:
      - colossus