name: stepsic-dev
channels:
  - bccp
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - toml
  - tabulate
  - h5py
  - numpy
  - scipy
  - astropy
  - camb
  - nbodykit
  - matplotlib
  - seaborn
  - pip
  - pip:
      - colossus